master:
  push:
    - imports:
      - https://cnb.cool/frigate-cn/github-key/-/blob/87d2daf01d7346e48f6d45986c579f82e28a4d57/github-token.yml
      - https://api.github.com/repos/blakeblackshear/frigate/releases/latest
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/Frigate-CN/fnnas.frigate.git
            auth_type: https
            username: ${github_username}
            password: ${github_access_token}
        - name: download fnpack cli
          script: curl -O https://static2.fnnas.com/fnpack/fnpack-1.0.4-linux-amd64
        - name: copy to usr
          script: |
            chmod +x fnpack-1.0.4-linux-amd64
            mv fnpack-1.0.4-linux-amd64 /usr/local/bin/fnpack
        - name: build fnpack
          script:
            fnpack build
        - name: create release
          type: git:release
          options:
            tag: $tag_name
            description: 飞牛专用插件
        - name: release 上传附件
          image: cnbcool/attachments:latest
          settings:
            type: UPLOAD
            tag: $tag_name
            attachments:
              - frigate.fpk