#!/bin/bash

CONTAINER_NAME="frigate"
FILE_PATH="${TRIM_APPDEST}/docker/docker-compose.yaml"
is_running() {
  docker inspect "$CONTAINER_NAME" 2>/dev/null | grep -q '"Status": "running"'
}

case $1 in
start)
    cd "$(dirname "$FILE_PATH")"
    docker compose -p frigate down
    docker compose -p frigate up -d
    exit $?
    ;;
stop)
    cd "$(dirname "$FILE_PATH")"
    docker compose -p frigate down
    exit $?
    ;;
status)
    if is_running; then
        exit 0
    else
        cd "$(dirname "$FILE_PATH")"
        docker compose -p frigate down
        docker compose -p frigate up -d
        exit 3
    fi
    ;;
*)
    exit 1
    ;;
esac