services:
  frigate:
    container_name: frigate
    extends:
      file: extends${wizard_version}${wizard_network_suffix}.yaml
      service: frigate
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    image: docker.cnb.cool/frigate-cn/frigate:0.18.0-beta1${wizard_version}
    shm_size: ${wizard_shm_size}
    devices:
      - /dev/dri/:/dev/dri/${wizard_coral}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TRIM_PKGETC}:/config
      - ${TRIM_PKGHOME}/video:/media/frigate
      - ${TRIM_APPDEST}:/app/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      TZ: "Asia/Shanghai"
      FRIGATE_BASE_PATH: "/app/frigate"
      HF_ENDPOINT: $wizard_endpoint
      GITHUB_ENDPOINT: $wizard_github_endpoint

  nginx:
    extends:
      file: extends-nginx${wizard_network_suffix}.yaml
      service: nginx
