services:
  frigate:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
